init:
 - set QTDIR=C:\Qt\5.9\mingw53_32
 - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
 
build_script:
  - cd Datalogger
  - qmake Datalogger.pro
  - mingw32-make
  
artifacts:
  - path: Datalogger\release\deploy
    name: windows
  - path: Datalogger\release\deploy\screenshot.png
    name: screenshot
  
after_build:
    - cd release
    - mkdir deploy
    - copy Datalogger.exe deploy
    - cd deploy
    - windeployqt Datalogger.exe
    - appveyor DownloadFile https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/screenshot-cmd/screenshot-cmd.exe
    - ps: start Datalogger.exe
    - screenshot-cmd.exe -wt "FRUCD Datalogger"
    - taskkill /IM Datalogger.exe
    
    
