init:
 - set QTDIR=C:\Qt\5.9\mingw53_32
 - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
 
build_script:
  - cd Datalogger
  - qmake Datalogger.pro
  - mingw32-make
  
artifacts:
  - path: Datalogger\release\deploy
    name: windows
  - path: Datalogger\release\screenshot.png
    name: screenshot
  
after_build:
    - cd release
    - mkdir deploy
    - copy Datalogger.exe deploy
    - cd deploy
    - windeployqt Datalogger.exe
    - cd ..
    - appveyor DownloadFile http://www.nirsoft.net/utils/nircmd-x64.zip
    - 7z x nircmd-x64.zip
    - ps: nircmd.exe cmdwait 3000 savescreenshot screenshot.png
    - ps: start deploy\Datalogger.exe
    
    
